name: toque_fale
description: Aplicativo Toque & Fale

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.3
  path: ^1.9.0
  flutter_tts: ^3.8.5
  sqflite_common_ffi_web: ^0.4.5
  flutter_application_1: ^0.0.2

flutter:
  uses-material-design: true